//
//  AudioSearchResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/AnyOptional/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class AudioSearchResp: NSObject, YYModel {
    
    var error_code: Int = 0
    
    var result: ResultBean?
    
    @objcMembers
    class ResultBean: NSObject, YYModel {
        
        var album_info: Album_infoBean?
        
        @objcMembers
        class Album_infoBean: NSObject, YYModel {
            var album_list: [Album_listBean]?
            
            @objcMembers
            class Album_listBean: NSObject, YYModel {
                var title: String?
                var author: String?
                var company: String?
                var hot: String?
                var all_artist_id: String?
                var artist_id: String?
                var publishtime: String?
                var pic_small: String?
                var resource_type_ext: String?
                var album_desc: String?
                var album_id: String?
            }
            
            var total: Int = 0
            
            static func modelContainerPropertyGenericClass() -> [String : Any]? {
                return ["album_list" : Album_listBean.self]
            }
        }
        
        var playlist_info: Playlist_infoBean?
        
        @objcMembers
        class Playlist_infoBean: NSObject, YYModel {
            var total: Int = 0
        }
        
        var video_info: Video_infoBean?
        
        @objcMembers
        class Video_infoBean: NSObject, YYModel {
            var total: Int = 0
        }
        
        var user_info: User_infoBean?
        
        @objcMembers
        class User_infoBean: NSObject, YYModel {
            var total: Int = 0
        }
        
        var song_info: Song_infoBean?
        
        @objcMembers
        class Song_infoBean: NSObject, YYModel {
            var song_list: [Song_listBean]?
            
            @objcMembers
            class Song_listBean: NSObject, YYModel {
                var ting_uid: String?
                var author: String?
                var progress: Int = 0
                var currentLength: Int = 0
                var title: String?
                var isPlaying: Bool = false
                var pic_small: String?
                var fileLength: Int = 0
                var has_mv_mobile: Bool = false
                var all_artist_id: String?
                var downloadState: Int = 0
                var isLike: Bool = false
                var album_title: String?
                var isLove: Bool = false
                var lrclink: String?
                var has_mv: Bool = false
                var song_id: String?
                var artist_id: String?
                var isDownload: Bool = false
                var album_id: String?
            }
            
            var total: Int = 0
            
            static func modelContainerPropertyGenericClass() -> [String : Any]? {
                return ["song_list" : Song_listBean.self]
            }
        }
        
        var artist_info: Artist_infoBean?
        
        @objcMembers
        class Artist_infoBean: NSObject, YYModel {
            var artist_list: [Artist_listBean]?
            
            @objcMembers
            class Artist_listBean: NSObject, YYModel {
                var ting_uid: String?
                var author: String?
                var song_num: String?
                var artist_id: String?
                var country: String?
                var artist_source: String?
                var artist_desc: String?
                var album_num: String?
                var avatar_middle: String?
            }
            
            
            static func modelContainerPropertyGenericClass() -> [String : Any]? {
                return ["artist_list" : Artist_listBean.self]
            }
        }
        
    }
}

