//
//  AudioSearchSuggestResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/AnyOptional/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class AudioSearchSuggestResp: NSObject, YYModel {
    
    var artist: [ArtistBean]?
    
    @objcMembers
    class ArtistBean: NSObject, YYModel {
        var artistid: String?
        var artistpic: String?
        var yyr_artist: String?
        var artistname: String?
        var weight: String?
    }
    
    var order: String?
    var album: [AlbumBean]?
    
    @objcMembers
    class AlbumBean: NSObject, YYModel {
        var weight: String?
        var albumname: String?
        var artistpic: String?
        var albumid: String?
        var artistname: String?
        var resource_type_ext: String?
    }
    
    var song: [SongBean]?
    
    @objcMembers
    class SongBean: NSObject, YYModel {
        var resource_type_ext: String?
        var artistname: String?
        var encrypted_songid: String?
        var yyr_artist: String?
        var info: String?
        var bitrate_fee: String?
        var resource_provider: String?
        var songname: String?
        var control: String?
        var songid: String?
        var resource_type: String?
        var weight: String?
        var has_mv: String?
    }
    
    var error_code: Int = 0
    
    static func modelContainerPropertyGenericClass() -> [String : Any]? {
        return ["artist" : ArtistBean.self,
                "song" : SongBean.self,
                "album" : AlbumBean.self]
    }
}

