//
//  AudioListResp.swift
//
//  This file is auto generated by fit.
//  Github: https://github.com/AnyOptional/fit
//
//  Copyright © 2018-present Archer. All rights reserved.
//

import YYKit

@objcMembers
class AudioListResp: NSObject, YYModel {
    
    var song_list: [Song_listBean]?
    
    @objcMembers
    class Song_listBean: NSObject, YYModel {
        var res_encryption_flag: String?
        var havehigh: Int = 0
        var pic_small: String?
        var file_duration: Int = 0
        var resource_type_ext: String?
        var pic_huge: String?
        var info: String?
        var album_800_800: String?
        var lrclink: String?
        var resource_type: String?
        var author: String?
        var song_id: String?
        var pic_big: String?
        var pic_premium: String?
        var album_500_500: String?
        var album_1000_1000: String?
        var artist_id: String?
        var album_title: String?
        var all_artist_id: String?
        var rank_change: String?
        var all_rate: String?
        var artist_name: String?
        var country: String?
        var ting_uid: String?
        var publishtime: String?
        var has_mv_mobile: Int = 0
        var title: String?
        var album_no: String?
        var mv_provider: String?
        var pic_radio: String?
        var biaoshi: String?
        var piao_id: String?
        var is_new: String?
        var album_id: String?
        var charge: Int = 0
        var pic_s500: String?
        var is_first_publish: Int = 0
        var rank: String?
        var versions: String?
        var si_proxycompany: String?
        var has_mv: Int = 0
        var all_artist_ting_uid: String?
        var style: String?
        var language: String?
        var bitrate_fee: String?
        var relate_status: String?
        var area: String?
        var korean_bb_song: String?
        var song_source: String?
        var toneid: String?
        var copy_type: String?
        var hot: String?
        var del_status: String?
        var has_filmtv: String?
        var learn: Int = 0
        var file_link: String? // additional
    }
    
    var error_code: Int = 0
    var billboard: BillboardBean?
    
    @objcMembers
    class BillboardBean: NSObject, YYModel {
        var pic_s210: String?
        var pic_s192: String?
        var billboard_songnum: String?
        var comment: String?
        var pic_s444: String?
        var billboard_type: String?
        var color: String?
        var havemore: Int = 0
        var pic_s640: String?
        var name: String?
        var update_date: String?
        var web_url: String?
        var pic_s260: String?
        var bg_color: String?
        var bg_pic: String?
        var billboard_no: String?
    }
    
    static func modelContainerPropertyGenericClass() -> [String : Any]? {
        return ["song_list" : Song_listBean.self]
    }
}
